

spring.datasource.postgres.jdbc-url=${PDB_URL}
spring.datasource.postgres.username=${PDB_USERNAME}
spring.datasource.postgres.password=${PDB_PASSWORD}
spring.datasource.postgres.driver-class-name=org.postgresql.Driver