

spring.datasource.mysql.jdbc-url=${DB_URL}
spring.datasource.mysql.username=${DB_USERNAME}
spring.datasource.mysql.password=${DB_PASSWORD}
spring.datasource.mysql.driver-class-name=com.mysql.cj.jdbc.Driver