package com.example.application.payment.dto;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(
        name = "VerifyPaymentRequest",
        description = "Request used to verify a payment after payment gateway completion"
)
public record VerifyPaymentRequest(

        @Schema(
                description = "Payment gateway order ID",
                example = "order_P7X82K91AB",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String orderId,

        @Schema(
                description = "Payment gateway payment ID",
                example = "pay_P9K72M31XY",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String paymentId,

        @Schema(
                description = "Payment signature generated by the payment gateway",
                example = "a8f7c6d5e4b3...",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String signature,

        @Schema(
                description = "Booking ID associated with the payment",
                example = "1001",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        Long bookingId
) {
}